spring:
  datasource:
    url: jdbc:mysql://localhost:3306/company?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml
    drop-first: false
  data:
    web:
      pageable:
        default-page-size: 15
        max-page-size: 50000
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

async:
  corePoolSize: 5
  maxPoolSize: 8
  queueCapacity: 100
  threadNamePrefix: "MyExecutor-"

import:
  executor:
    corePoolSize: 1
    maxPoolSize: 1
    queueCapacity: 10
    threadNamePrefix: "ImportExecutor-"

batch:
  size: 1000
